ㅊㅊ

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -1,52 +1,51 @@
-  name: 배포
+name: 배포
 
-  on:
-    push:
-      branches: ["main"]
+on:
+  push:
+    branches: ["main"]
 
-  jobs:
-    deploy-backend:
-      runs-on: ubuntu-latest
-      steps:
-        - name: 체크아웃
-          uses: actions/checkout@v4
-        - name: JDK 17 사용
-          uses: actions/setup-java@v4
-          with:
-            java-version: "17"
-            distribution: "temurin"
-        - name: Gradle Wrapper 실행 권한 추가
-          run: chmod +x gradlew
-        - name: Gradle로 빌드
-          run: ./gradlew build -x test
-        - name: 도커허브에 로그인
-          uses: docker/login-action@v3
-          with:
-            username: ${{ secrets.DOCKER_USER_NAME }}
-            password: ${{ secrets.DOCKER_USER_PW }}
-        - name: 이미지 빌드
-          run: docker build -t ${{ secrets.DOCKER_USER_NAME }}/${{ secrets.DOCKER_IMAGE_NAME }}-be .
-        - name: 도커허브에 이미지 푸시
-          run: docker push ${{ secrets.DOCKER_USER_NAME }}/${{ secrets.DOCKER_IMAGE_NAME }}-be
-        - name: AWS EC2에 ssh 접속 후 배포
-          uses: appleboy/ssh-action@v1.0.3
-          with:
-            host: ${{ secrets.AWS_IP }}
-            port: 22
-            username: ubuntu
-            key: ${{ secrets.AWS_KEY }}
-            script: |
-              sudo timedatectl set-timezone Asia/Seoul
-              export PATH=$PATH:/usr/local/bin:/usr/bin
-              if [ -z "${{ secrets.DOCKER_COMPOSE_YML }}" ]; then
-                echo "Error: DOCKER_COMPOSE_YML is empty"
-                exit 1
-              fi
-              echo "${{ secrets.DOCKER_COMPOSE_YML }}" > /home/ubuntu/docker-compose.yml
-              echo "${{ secrets.ENV_FILE }}" > /home/ubuntu/.env
-              chmod 600 /home/ubuntu/.env
-              docker pull ${{ secrets.DOCKER_USER_NAME }}/${{ secrets.DOCKER_IMAGE_NAME }}-be
-              docker pull ${{ secrets.DOCKER_USER_NAME }}/${{ secrets.DOCKER_IMAGE_NAME }}-front
-              docker compose -f /home/ubuntu/docker-compose.yml down
-              docker volume prune -f
-              docker compose -f /home/ubuntu/docker-compose.yml up -d --force-recreate
+jobs:
+  deploy-backend:
+    runs-on: ubuntu-latest
+    steps:
+      - name: 체크아웃
+        uses: actions/checkout@v4
+      - name: JDK 17 사용
+        uses: actions/setup-java@v4
+        with:
+          java-version: "17"
+          distribution: "temurin"
+      - name: Gradle Wrapper 실행 권한 추가
+        run: chmod +x gradlew
+      - name: Gradle로 빌드
+        run: ./gradlew build -x test
+      - name: 도커허브에 로그인
+        uses: docker/login-action@v3
+        with:
+          username: ${{ secrets.DOCKER_USER_NAME }}
+          password: ${{ secrets.DOCKER_USER_PW }}
+      - name: 이미지 빌드
+        run: docker build -t ${{ secrets.DOCKER_USER_NAME }}/${{ secrets.DOCKER_IMAGE_NAME }}-be .
+      - name: 도커허브에 이미지 푸시
+        run: docker push ${{ secrets.DOCKER_USER_NAME }}/${{ secrets.DOCKER_IMAGE_NAME }}-be
+      - name: AWS EC2에 ssh 접속 후 배포
+        uses: appleboy/ssh-action@v1.0.3
+        with:
+          host: ${{ secrets.AWS_IP }}
+          port: 22
+          username: ubuntu
+          key: ${{ secrets.AWS_KEY }}
+          script: |
+            sudo timedatectl set-timezone Asia/Seoul
+            export PATH=$PATH:/usr/local/bin:/usr/bin
+            if [ -z "${{ secrets.DOCKER_COMPOSE_YML }}" ]; then
+              echo "Error: DOCKER_COMPOSE_YML is empty"
+              exit 1
+            fi
+            echo "${{ secrets.DOCKER_COMPOSE_YML }}" > /home/ubuntu/docker-compose.yml
+            echo "${{ secrets.ENV_FILE }}" > /home/ubuntu/.env
+            chmod 600 /home/ubuntu/.env
+            docker pull ${{ secrets.DOCKER_USER_NAME }}/${{ secrets.DOCKER_IMAGE_NAME }}-be
+            docker compose -f /home/ubuntu/docker-compose.yml down
+            docker volume prune -f
+            docker compose -f /home/ubuntu/docker-compose.yml up -d --force-recreate
